#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)
ADMIN_PASSWORD = data.get('ADMIN_PASSWORD', "password")
#This is specific to you module, so you need to change it accordingly.
HOST = data.get('host')
chibi = {
    "BASE_API_URL": f'chibisafe-server:8000',
    "BASE_URL": "https://"+HOST,
    "ADMIN_PASSWORD": ADMIN_PASSWORD
}
agent.write_envfile('chibi.env', chibi)
#agent.dump_env()
